### ISSUE TITLE
Jupyter isn't showing all enviroments

### ISSUE THREAD

**Issue by alealv** [Anaconda-Platform/nb_conda#60] opened 2017-09-07 20:42 UTC
Hi, I'm having this annoying problem.

If I list all the current environments I get:
```
alejandroalvarez@PMITN010321:~$ conda info --envs
# conda environments:
#
imgqlty                  /home/alejandroalvarez/anaconda3/envs/imgqlty
opencv                   /home/alejandroalvarez/anaconda3/envs/opencv
root                  *  /home/alejandroalvarez/anaconda3
```

But then, after launching jupyter, it doesn't show the opencv environment!

```
alejandroalvarez@PMITN010321:~$ jupyter notebook
[I 17:35:20.162 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
[I 17:35:20.534 NotebookApp] The port 8888 is already in use, trying another port.
[I 17:35:20.625 NotebookApp] [nb_anacondacloud] enabled
[I 17:35:20.652 NotebookApp] [nb_conda] enabled
[I 17:35:20.693 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 17:35:20.693 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 17:35:20.695 NotebookApp] Serving notebooks from local directory: /home/alejandroalvarez
[I 17:35:20.695 NotebookApp] 0 active kernels 
[I 17:35:20.695 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=bd6abbee010d501676c4bab364985aa52fd38d7c68b16298
[I 17:35:20.695 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:35:20.697 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=bd6abbee010d501676c4bab364985aa52fd38d7c68b16298
[25343:25378:0907/173521.029754:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Created new window in existing browser session.
[I 17:35:21.041 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1

```

![screenshot from 2017-09-07 17-38-36](https://user-images.githubusercontent.com/9395091/30184199-9a270c58-93f3-11e7-9b4c-52bd6fa5cb8c.png)

Can you give me a hand with this?

**Comment by ijstokes** [comment] 2017-09-07 21:12
I believe the issue is that the `opencv` environment needs to also have some the `ipykernel` Jupyter package.  Also, this issue should probably be in this issue tracker:

https://github.com/Anaconda-Platform/nb_conda_kernels/

`nb_conda` gives you some control of conda environments and conda packages from inside Jupyter, whereas `nb_conda_kernels` is the thing that actually creates the list you've shown in your screenshot above.  The GH `README.md` file for `nb_conda_kernels` provides some more details.  I'm going to close this, but open it again if you think the problem persists after you've done:

```
conda install -n opencv ipykernel
```

**Closed by ijstokes** 2017-09-07 21:12 UTC

**Comment by alealv** [comment] 2017-09-08 14:04
Thank you! Now it's solved.
